### ISSUE TITLE
Custom Internal port

### ISSUE THREAD

**Issue by prom3theu5** [TheWicklowWolf/eBookBuddy#3]
This is great
Any chance you could make the internal port (5000) configurable from env as well?
I tend to have everything running through gluetun, and I'd have a conflict on internal 5000 if I did here
Same with book bounty please :)

**Comment by TheWicklowWolf** [comment]
This uses web scraping (as there is no decent APIs available) so don't expect it to be too reliable...

No plans to make the internal port configurable, as a workaround see this from @TheLazyGeekGuy
https://github.com/TheWicklowWolf/Lidify/issues/3#issuecomment-2187351431

> Download and modify gunicorn_config.py with the correct local port you want, mount it as a .. file !
> 
> it does the job :)
> 
> ```
>     volumes:
>       - /local_path/gunicorn_config.py:/lidify/gunicorn_config.py
> ```

Use the same method for BookBounty.
