### ISSUE TITLE
500 error on api

### ISSUE THREAD

**Issue by soupofstars** [TheWicklowWolf/eBookBuddy#9]
Hi,  

Getting a 500 error code in the gui when requesting to read readarr books.

Error Getting Book list from Readarr: HTTPConnectionPool(host='172.16.10.109', port=8787): Max retries exceeded with url: /api/v1/author (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x14b042b01430>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

I have tripple checked ip address, port and api key

**Comment by soupofstars** [comment]
Because I'm using Unraid the 5000 port is clashing with ebookbounty

**Comment by TheWicklowWolf** [comment]
Use a different port/


---

No plans to make the internal port configurable, as a workaround see this from @TheLazyGeekGuy
https://github.com/TheWicklowWolf/Lidify/issues/3#issuecomment-2187351431

> Download and modify gunicorn_config.py with the correct local port you want, mount it as a .. file !
> 
> it does the job :)
> 
> ```
>     volumes:
>       - /local_path/gunicorn_config.py:/lidify/gunicorn_config.py
> ```
